### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by innoreq** [backbee/backbee-php#705]
Although BackBee is an interesting tool, it is not possible for us to use it, as our hosted space does not allow for the installation and/or use of Composer. Therefore, there should be an installation process / distributable that can be installed on a machine with LAMP setup and no root access.

**Comment by crouillon** [comment]
Hi @innoreq,

We now provide an archive of the standard distribution of BackBee including every needed dependencies.
Please take a look at http://backbee.com/backbee/backbee-latest.zip

This archive should be uncompress in the document root of your hosted space, then launch http://<<your_domain_name>>/public/ to start the installation process.

Regards
Charles
